### ISSUE TITLE
[Request] Custom file format name is not saved

### ISSUE THREAD

**Issue by MageNext** [marvinweber/KPSimpleBackup#12]
I am using a custom file format for additional security (no kdbx). I tried database / file name change, and also plugin / Advanced / Use db name. But the backup files all have kdbx.

Is it possible to use the file name without kdbx and at the end date? Thanks.

**Comment by marvinweber** [comment]
No, currently that is not possible but - as i think of it - it would indeed make sense.  
I will try to implement it within the next feature-release :)

**Comment by marvinweber** [comment]
✅ Use original file extension as backup-file extension. In the settings it's also possible now to define an alternative file extension that should be used instead for all backups.

ℹ️ This will be **released with v1.2.0 within the next few days**.
