### ISSUE TITLE
relative paths

### ISSUE THREAD

**Issue by upD8R** [marvinweber/KPSimpleBackup#19]
Hi there,

thanks for this nice plugin. Basically, I host Keepass on my private cloud (Seafile) and I'd like to backup to a subfolder in the actual Keepass directory.
So, I would like to give a relative path and not an absolute one because the Keepass folder has different absolute paths (depending an what PC I use the Seafile sync software). Seafile works similar as Dropbox, so you can define where it should create a sync folder and sometimes this is on C:\ or D:\ or E:\.

I didn't find an official way to enter relative paths but I changed the backup path entry in the KeePass.config.xml in the following way:
```
		<Item>
			<Key>KPSimpleBackupConfig_backupPath</Key>
			<Value>./Seafile/Keepass/Backups/</Value>
		</Item>
```
This works with two exceptions:
a) An error message in the session log that the DB backup failed (actually, it did NOT fail).
b) outdated backups won't be deleted

Maybe you can look into this, at least b) is a bit annoying.

Thanks!

**Comment by marvinweber** [comment]
Hey :)  
Thanks for reporting this issue!

I'll have a look at it 👍

**Comment by marvinweber** [comment]
**FYI**: Starting with the next release of KPSimpleBackup ([Version 1.3](https://github.com/marvinweber/KPSimpleBackup/milestone/1)) you will be able to add relative backup paths in the _Advanced_ section of the settings.  
Cleanups should work now also properly.
