### ISSUE TITLE
Multiple Backups (with timestamps) for KeePass Configuration File

### ISSUE THREAD

**Issue by ElTopo** [marvinweber/KPSimpleBackup#25]
KeePass version: 2.45 (on Windows 10)
KPSimpleBackup version: 1.3.0.0

I enabled "Backup KeePass configuration file (KeePass.config.xml)" in additional settings, and "Long-Term-Backups" in Advanced.

When I check the backup files, I see 2 problems:
1. the config file is backed up as "KeePass.config.xml.backup-application-config" without proper timestamp, which means, only **1 backup** will be created and it'll overwrite any old copies, while I expected that the config file should be backed up with timestamp, similar to database file;
2. the config file is not backed up in long term backup folders (weekly/monthly/yearly)

**Comment by marvinweber** [comment]
Hi :)
Currently this is intended behaviour.  
This feature was added in #16 , to be able to restore window layout and formatting. While I can see various use cases where its useful to be able to restore older database versions, i cannot see such a use case for the KeePass file.
What is the actual reason, that you need it with a timestamp and in the ltb-folders? :)

**Comment by ElTopo** [comment]
@marvinweber Thanks for the reply.

I usually synchronize my KeePass (portable) database and config between multiple devices using a cloud storage service. Several months ago, the cloud service messed up something and incorrectly used an older version to overwrite my KeePass database and config, not only I lost my window layout and formatting, I also lost some of app settings and plug-in settings (including KPSimpleBackup's), and some plug-ins stopped working completely. Fortunately the cloud service keeps file histories and I was able to recover from cloud.
That was when I found KPSimpleBackup could not help me with config file: there's only 1 copy of the incorrect config file. After all, if I have database file history backed up with timestamp, I don't see the reason why KeePass.config.xml is only saved with the last version. I know not everyone wants or needs KeePass.config.xml history, but please, at least make it optional for us who do want it.

**Comment by ams-tschoening** [comment]
If you actually want to version textual config files, think about using Source Code Management like GIT or SVN instead. That way you can maintain each and every change to your configs, compare those, document those etc. That doesn't work very well for binary, encrypted databases, so that additional backup plugins make sense for those. But configs are better placed in GIT or SVN instead and it's really easy to use as well.

**Comment by marvinweber** [comment]
I generally agree to @ams-tschoening .
However, for simplicity and users not familiar with these "options" I will add timestamps to the backed up config files. :)
But adding LTB functionality would require more effort and, thus, I will not add LTB support.

**Comment by marvinweber** [comment]
Starting with Version 1.4, the backups of the config files will be created with a timestamp. Similar to the normal database backup, old config backup files will be removed (amount to keep depends on the configuration).

**Comment by ElTopo** [comment]
I generally DON'T agree with @ams-tschoening, especially at an issue page of KPSimpleBackup.

Sure there are other ways to do backup, I could use git to do it, I could use cron+rsync to do it, I could use [insert other backup software here] to do it.

Then why should I choose KPSImpleBackup?

Anyway, thanks for the new release and I promise I won't complain anymore.
