### ISSUE TITLE
If option 'Backup database when it's being closed or when the KeePass application is being closed' is disabled, it saves the database when the database is being locked

### ISSUE THREAD

**Issue by jon-f-novastor** [marvinweber/KPSimpleBackup#26]
Using KSSimpleBackup v1.3, if the option 'Backup database when it's being closed or when the KeePass application is being closed' **is disabled**, **it still saves the database right when the workspace is locked, whether if a manual lock or when the auto lock trigger is hit**. With that option disabled, **it should only save either when the database is being closed or the app is being closed** according to the option description. If I turn off that option and lock the database, it does not save so I know KeePass v2.4.5 is not attempting that save and KSSimpleBackup v1.3 is doing it. It does not seem to matter what combination of options I'm using, if this option is unchecked it will always save the database when only locking the database either manually using 'Lock Workspace' function, or automatically based on the auto-lock timer option value in KeePass v2.4.5. See here for the option text in KSSimpleBackup v1.3:

![image](https://user-images.githubusercontent.com/50121594/91602749-b4d05980-e920-11ea-8123-4eabf9f43c98.png)

Can there be an option / method of using KSSimpleBackup where it only saves the database when the database is being closed or the app is being exited from (or when the manual 'Backup Database now!' menu item is clicked)? That would be in addition to the 'Backup Database now!' function via the plugin menu. Thank you in advanced, and for the great plugin!

**Comment by jon-f-novastor** [comment]
With this option unchecked it still may bother some to do all of the saves to multiple backup locations including two cloud locations, including Long Term Backup saves, each time the Workspace Lock is called or the automatic workspace lock is triggered by the timer setting in KeePass.  In this case it has to sit there saving all of the databases each time the workspace locks, in my case that is 45 seconds in total, which means I cannot get back in to untray the application while it is doing that save.  As suggested by wellread1 it would be a great idea to be able to have a new option that allows a time-periodic type of save whereby it calls the "Backup Database now!" function after a set number of idle time in minutes (idle time using KeePass) is reached.

**Comment by marvinweber** [comment]
Honestly, I was not able to reproduce your issue.

There are two "triggers" that start a backup, these are:
- Whenever the database is being saved (by you manually, or automatically). This is the "Auto-Backup Database" option under "Advanced > General Backup Options".
- Whenever the database is closed/locked or KeePass is closed. This is the option you mentioned intially in your issue ("Backup database when it's being closed or when the KeePass application is being closed")

You can enable or disable one or both options. For me, this works as expected.  
Could you please specify again what your exact problem is? Thank you!

**Comment by jon-f-novastor** [comment]
It looks good when I retested with v1.4 just now; I do thank you for changing the description of the option because it was not worded well to know exactly how it worked.  In v1.4 the description the same option is good and it works as expected in this version.  Thanks for all the work!

v1.4 Advanced Settings:
![image](https://user-images.githubusercontent.com/50121594/114466624-93fe0100-9b9d-11eb-9bfc-6f93e4dac92a.png)
