### ISSUE TITLE
Doesn't appear installed

### ISSUE THREAD

**Issue by nollinvoyd** [marvinweber/KPSimpleBackup#52]
I tried both installation methods. [https://github.com/marvinweber/KPSimpleBackup/wiki/Installation](url) 

I don't see it in the tools menu or plugins submenu

**Comment by marvinweber** [comment]
Hi, without any more context, its hard to help you here.

If you click "Tools" > "Plugins" in the Menu bar of KeePass, do you see the Plugin listed there?  
If not, if you click on "Open Folder" in that same window on the bottom, is that the folder where you put the plugin files to?

**Comment by nollinvoyd** [comment]
Sorry, It's there now, but I'm not sure what I was doing wrong before.  I had to put KPSimpleBackup.plgx & both .ddl's in the plugin folder.  I thought I did that before, but apparently not?

**Comment by marvinweber** [comment]
Ok, glad it works now :)

Usually, either `plgx` or the `dll` files should be sufficient.
