### ISSUE TITLE
Enforced Config File not backuped

### ISSUE THREAD

**Issue by edguitton** [marvinweber/KPSimpleBackup#56]
Hello !
Since Keepass 2.54, when you customize some settings like URL Override, an enforced configuration file is created : KeePass.config.enforced.xml

this file is actually not and should be saved by KPSimpleBackup if "backup keepass configuration file" is selected.

Please consider adding this file to the backup, otherwise on reinstallation on a new computer, the config of keepass is uncomplete and you can't easily restore the complex URL override you've worked through (I have more than 30, ;D).

Thanks, keep up the good work, I need only 2 plugins to keepass, and KPSimpleBackup is one of them <3

Sincerely.

Edit : more info on enforced config files : https://keepass.info/help/kb/config_enf.html

**Comment by marvinweber** [comment]
Thanks for your input, will by coverd by #57
