### ISSUE TITLE
Working with latest Keepass 2.57?

### ISSUE THREAD

**Issue by pommer-12** [marvinweber/KPSimpleBackup#59]
Is the Plugin still running with the latest version of Keepass 2.57? I get an error message using the latest portable version that the plugin ist not compatible. With older versions it worked.

Thank you! I highly appreciate your tool !!!

**Comment by gusowski1** [comment]
i doesn't have any issues.
Whats the error?

**Comment by pommer-12** [comment]
Oh, sorry, I checked and updated everything again, and now it does work properly. I don't know what caused the error yesterday.
Sorry again!
