### ISSUE TITLE
Long-Term-Backups - Keep single copies of older backups in periods

### ISSUE THREAD

**Issue by marvinweber** [marvinweber/KPSimpleBackup#8]
Keep weekly / monthly / yearly older backups (no matter if backup-limit is reached)

### Goal
Keep the following types of backup:
* One backup of the **last 4 weeks**
* One backup of the **last 12 months**
* One backup of **every year**

This feature should be enabled (and disabled) in the advanced settings.

---

> I would however give a suggestion
> a separate line of backups that only save if its a new week or month
> So you would have the normal 20  backups tha is everytime you save.
> but also lets say 4 that each is one week/month in between.
> This would help agiant saturating the normal number of backups during  time with a lot of changes and then suddenly realise you delete once a bit earlier.
> 
> Example
> Database_Week05
> Database_Week06
> Database_Week07
> Databsae_Week08

_originally posted by @SvenBent in https://github.com/marvinweber/KPSimpleBackup/issues/5#issuecomment-525524612_

**Comment by mustelid** [comment]
Also, please bump up the maximum number of backups that can be kept to at least a thousand. (The spin box currently maxes out at 100).

**Comment by marvinweber** [comment]
> Also, please bump up the maximum number of backups that can be kept to at least a thousand. (The spin box currently maxes out at 100).

@mustelid This will be released in the next feature release v.1.2 within the next few days :) (see #11)

**Comment by marvinweber** [comment]
This has been released with v1.2 today.
