### ISSUE TITLE
[Request] Automatic single backup each session

### ISSUE THREAD

**Issue by Taomyn** [marvinweber/KPSimpleBackup#9]
Would it be possible to have an option that backs up the database just once per session or at least some kind of scheduler for it?

Backing up for every change is a bit overkill for me and also when it's on a slowish device/media it becomes annoying.

**Comment by marvinweber** [comment]
Thanks for that suggestion!

I'll try to address that within the next feature release 👍

**Comment by marvinweber** [comment]
✅ Added new option in the advanced settings to enable backing-up the database when the database file or the entire KeePass-application is being closed.
ℹ️ This will be released with **v1.2.0 within the next few days**!

---
@Taomyn: By disabling auto-backup and enabling the new "Backup, when database is being closed" option in the **advanced settings**, it should result in your desired behaviour :)
